# Site settings
title: "Toolary - 24 Productivity Tools for Modern Web"
description: "A comprehensive Chrome extension with 24 web productivity tools including AI-powered features, smart favorites, and modern design"
url: "https://ademisler.github.io/toolary.github.io/"
baseurl: "/toolary.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
author: "Adem İşler"
twitter: "@idemasler"
github: "ademisler"
linkedin: "idemasler"

# Site configuration
timezone: Europe/Istanbul
lang: en
encoding: utf-8

# Collections
collections:
  tools:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Adem İşler"

# Exclude from processing
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .gitignore
  - .DS_Store
  - extension/
  - test/
  - coverage/
  - toolary-v2.0.0.zip
  - son.zip

# Include
include:
  - _pages

# Sass configuration
sass:
  sass_dir: assets/css
  style: compressed

# Jekyll SEO Tag
social:
  name: "Toolary"
  links:
    - "https://github.com/ademisler"
    - "https://ademisler.com/en"
    - "https://buymeacoffee.com/ademisler"

# Google Analytics (add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Disqus (add your shortname)
# disqus:
#   shortname: your-disqus-shortname
